-- ============================================================
-- 巡逻状态 - patrol_state.lua
-- 
-- 对外接口（必须实现）：
--   local state = {}
--   state.name = "patrol"
--   function state.Enter(enemy)   -- 进入时调用，enemy 是 C# Enemy 对象
--   function state.Update(enemy)  -- 每帧调用，return 下一个状态名 或 nil
--   function state.Exit(enemy)    -- 退出时调用
--   return state
--
-- C# Enemy 上可用的字段/方法（通过 enemy.xxx 访问）：
--   enemy.transform.position     -- 当前位置
--   enemy.rb.velocity            -- Rigidbody2D 速度
--   enemy.startPos               -- 初始位置（Vector3）
--   enemy.chaseRange             -- 追击范围
--   enemy.territoryRange         -- 领地范围
--   enemy.moveSpeed              -- 移动速度
--   enemy:CanSeePlayer()         -- 返回 bool
--   enemy:UpdateVisuals()        -- 更新动画/视觉效果
--   CS.UnityEngine.Time.time     -- 游戏运行时间
--   CS.UnityEngine.Vector2(x, y) -- 创建二维向量
--
-- 提示：可以做余弦振动巡逻，也可以自定义任何巡逻逻辑
